DATA_VALIDATION_DIR = "data_validation"
DATA_VALIDATION_TRAIN_DIR = 'train_dir'
DATA_VALIDATION_TEST_DIR = 'test_dir'
DATA_VALIDATION_FILE_NAME_TRAIN = "train_churn"
DATA_VALIDATION_FILE_NAME_TEST = "test_churn"